version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 8.a, < 9"
  - dependency-name: doctrine/dbal
    versions:
    - 2.13.0
  - dependency-name: mockery/mockery
    versions:
    - 1.3.3
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - 15.10.0
    - 15.11.0
    - 15.12.0
    - 15.13.0
    - 15.14.0
    - 15.7.0
    - 15.8.0
    - 15.9.0
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: refactor/actix-rewrite
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: futures-sink
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: encoding_rs
    versions:
    - 0.8.26
