sudo: required
dist: trusty
language: php
php:
    - 7
    - 7.1

addons:
    mariadb: "10.0"

cache:
    directories:
    - "$HOME/.composer/cache/files"
    - "$HOME/.npm"
    - "$HOME/.cache/bower"

env:
    global:
    - WIWU_TEST=php

matrix:
    include:
    - php: 7
      env: WIWU_TEST=lint_php
    - php: 7.1
      env: WIWU_TEST=lint_php
    fast_finish: true

branches:
   only:
   - master

before_script:
    # Faster builds if we don't need xdebug
    - if [[ "$WIWU_TEST" != "php" ]]; then phpenv config-rm xdebug.ini; fi

    # Install js deps
    - npm install
    - ./node_modules/bower/bin/bower install

    # Install php deps
    - composer install

    # Set up DB
    - mysql -u root -e 'create database wiwu_test;'
    - mysql -u root -e "CREATE USER 'wiwu'@'localhost' IDENTIFIED BY 'test';"
    - mysql -u root -e "GRANT SUPER on *.* to 'wiwu'@'localhost';"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON wiwu_test.* TO 'wiwu'@'localhost';"

    # Copy environment file
    - cp tests/test.env .env
    - cat .env

script:
    - echo "test suite $WIWU_TEST"

    # Optimize/bundle js
    - ./node_modules/requirejs/bin/r.js -o build.js

    # PHP
    - if [[ "$WIWU_TEST" = "php" ]]; then ./build/test_php.sh; fi

    # Check PHP syntax
    - if [[ "$WIWU_TEST" = "php_lint" ]]; then find . -name \*.php -not -path './vendor/*' -exec php -l "{}" \;; fi

after_script:
    - if [[ "$WIWU_TEST" = "php" ]]; then cat storage/logs/laravel.log; fi
